[default]
num_epochs = 10
batch_size = 4

learning_rate = 1e-3
weight_decay = 0.0005
momentum = 0.9
step_size = 5
gamma=0.1

[dev]
num_epochs = 40
batch_size = 2

learning_rate = 1e-3
weight_decay = 0
momentum = 0.9
factor = 0.5
patience = 3
swa_lr = 1e-5
anneal_epochs = 1
