[default]
num_epochs = 10
batch_size = 4

learning_rate = 1e-3
weight_decay = 0.0005
momentum = 0.9
step_size = 5
gamma=0.1

[dev]
num_epochs = 50
batch_size = 4

learning_rate = 1e-3
weight_decay = 0.0005
momentum = 0.9
step_size = 5
gamma=1.0
